services:
    aws_relay:
        build: .
        volumes:
            - ./config:/app/config
            - ./certs:/app/certs
        networks:
            default:
        logging:
            driver: syslog
            options:
                tag: docker-aws-relay
        restart: unless-stopped
