services:
  aws_relay:
    extends:
      file: aws_relay/app.yml
      service: app
    networks:
      default:
    logging:
      driver: syslog
      options:
        tag: docker-aws-relay
    restart: unless-stopped
